### ISSUE TITLE
Hamlets (and localities ?)

### ISSUE THREAD

**Issue by adelcasse** [CanalTP/mimirsbrunn#172]
Hi,

Currently, OSM hamlets (and probably localities ?) are not imported in Elasticsearch indexes and cannot be searched. It can be a problem in some rural areas where people's addresses are only hamlets or localities names, without any street or house number.

As hamlets and localities are coded as points ("place:hamlet"/"place:locality") in OSM, they cannot be integrated in administrative areas (and are not, in an institutional point of view) neither in streets. I made a change locally to integrate them as POI.

To have an idea of the impact, this leads, in the Provence-Alpes-Cote-d'Azur region in France I tested, and only for hamlets (I didn't test with localities), to a 1.5/2% increase of records stored in the POI index.

Another way may be to create a new type of data alongside steets, administrative areas, POI and stop points ? Eventually optional ?

Is there interest in integrating halmets and localities ? If so, I could look at it and contribute (beware, I'm completely new to your project ;)).

Best Regards
Arnaud

**Comment by TeXitoi** [comment]
You can integrate hamlets and localities in POI just by giving a conf file to osm2mimir. Is that what you've done?

Generally, we think that POIs need love, by importing much more kind of object, and improving the score by poi type (having a VLS station when you type a road name is not great).

**Comment by TeXitoi** [comment]
The option is `--poi-config`, and the default value if this argument is not given is https://github.com/CanalTP/mimirsbrunn/blob/master/src/osm_reader/poi.rs#L126-L191 (a good base to customize for your needs).

**Comment by adelcasse** [comment]
Thanks a lot for this answer : I didn't see the --poi-config option, I'll take a look, I changed the default value here https://github.com/CanalTP/mimirsbrunn/blob/master/src/osm_reader/poi.rs#L126-L191 in fact. My bad ...

**Comment by TeXitoi** [comment]
the rules are:
 - all osm_tags_filter must match;
 - first matching rule apply.

**Comment by adelcasse** [comment]
Closing it as it's OK
