### ISSUE TITLE
More centralized admin handling

### ISSUE THREAD

**Issue by antoine-de** [CanalTP/mimirsbrunn#176]
Hi all,

In osm2mimir there is a `city_level` to be able to determine which admin is a city.

We also need to know if and admin is a city in openaddresses2mimir (and in bano too even if we can hardcode the french osm `admin_level` to 8).

I think we can just add a `type` to the admin.

To be able to have finer grained types i think the best approach is an enum:

```rust
enum AdminType {
    City,
    Unkown
};
```

In the future we could add [libpostal hierarchy](https://github.com/openvenues/libpostal#parser-labels) or [Wof hierarchy](https://github.com/whosonfirst/whosonfirst-placetypes), but that's another story :wink: 

For the naming, i'm not convinced by `type`, do you have better alternative ? `level` is not available since it would break retro compatibility.

If you agree on this, we're willing to implement it.

**Comment by kinnou02** [comment]
Sound good for me. `Type` isn't so bad.

**Comment by TeXitoi** [comment]
That's may be more complex. You don't want only city, you want all the interesting admins. For France, it should be City, France; and for USA, City, State, USA.

**Comment by antoine-de** [comment]
that's why it's an enum open to modification, wait for the coming issue
:wink:

**Comment by antoine-de** [comment]
I created the new issue #178
