### ISSUE TITLE
Manage depedencies between imports

### ISSUE THREAD

**Issue by TeXitoi** [CanalTP/mimirsbrunn#177]
From now, we have OSM and Bano/OpenAddresses. OSM import admins, streets and POIs. Bano/OpenAddresses imports addresses. Addresses depends on admins, streets depends on admins, and POIs depend on admins and addresses.

Thus, we need to import OSM => Bano/OpenAddresses => OSM, that's not so clean.

I don't know how to fix that. Maybe cutting osm in admin, street and poi import (it's quite buggy now) and force the  order of imports by type and not by data.

**Comment by antoine-de** [comment]
the OSM => OA dependency might be fixed by the 2nd solution of #178

**Comment by antoine-de** [comment]
with cosmogony2mimir we can close this, the canonical import process is:
cosmogony -> bano/oa -> osm (only for streets and sometimes POI)
