### ISSUE TITLE
Worldwide administrative regions

### ISSUE THREAD

**Issue by antoine-de** [CanalTP/mimirsbrunn#178]
Hi all,

One of the biggest problem for mimir to go worldwide :world_map: is the admin handling :sob: 

For the moment mimir has a very basic admin handling based on a cli configured `admin_level` that can be configured once per `dataset`.

The [admin level](https://wiki.openstreetmap.org/wiki/Tag:boundary%3Dadministrative) can be quite complex since they are different for each countries.

## Current limitations

The current approach has several downsides:
* we cannot import the world as one, we need at least `dataset`s with countries with the same admin level
* This `city` stuff is used only for label formating, but this is a larger problem than just a city detection (in some countries we might want the `state`, or the `region` or whatever is relevant in the country

## Back to the roots, why do we need this ?

In my understanding we need the administrative regions for:
 1. disambiguation: 
    a bad term, but it's essential to handle the admins because objects (street, address, pois and even admins themselves) are unique only in their admin context.
    So it's very important to be able the search `20 rue hector malot paris` and not have the `20 rue hector malot` in lyon. 
    For the admins it's the same, the difference between [paris france](http://www.openstreetmap.org/relation/7444) and [paris us](http://www.openstreetmap.org/relation/6678712) is their admin context (at least the countries)
 2. the response formatting: 
    In mimir the `admin_level` (or admin's `type` in #176) is used for the moment only for label formatting.
    It's nice for the `20 rue hector malot` to have a label like `20 rue hector malot (Paris)` at least because the `label` must be unique in the API's response for the user to be able to choose between `20 rue hector malot paris` and `20 rue hector malot in lyon`
 3. better search:
    It's not done for the moment, but the admin hierarchy might help if one day mimir use [libpostal](https://github.com/openvenues/libpostal) as we could do structured search. I will not detail this as it's not very important and quite a long shot.

For `1.` (and even maybe `3.`) we need the administrative hierarchy, but I don't think the admin's `type` is important. For disambiguation, linking an object to all it's admins without knowing which is the city, which is the region might be enough.

For `2.` though we need to know which one is the city (and to do correct i10n, we should also know which is the `region`, which is the `country`, ..., but i10n label formatting is a story for another issue :wink:)

## What the others do

The subject is quite difficult and has been tackled quite differently other places:
* [pelias](https://github.com/pelias/pelias/) use [WhosOnFirst](https://www.whosonfirst.org/) to handle this complexity
* [osmnames](http://osmnames.org/) has quite an [interesting approach](https://github.com/OSMNames/OSMNames/pull/82), but I don't think it works everywhere (especially in Germany with their [twisted admin hierarchy](https://de.wikipedia.org/wiki/Datei:Administrative_Gliederung_Deutschlands.svg) )
* [libpostal](https://github.com/openvenues/libpostal) has a [lot of rules](https://github.com/openvenues/libpostal/blob/master/resources/boundaries/osm/fr.yaml)

### Keep the cli based osm2mimir configuration

Instead of the `city_level`, we could give a more complex configuration associating a `admin_level` to an `AdminType`.

:white_check_mark: easy to implement
❌ impossible to make a world import, we need to split into dataset with the same configuration
❌ hard to maintain all the configuration

### Export the complexity to another place

A bit like the [osmnames's export](http://osmnames.org/download/) or [WhosOnFirst](https://www.whosonfirst.org/) approach, we could make another project that aim is to eat an osm file (and maybe something like [the countries shapes](https://raw.githubusercontent.com/OSMNames/OSMNames/master/data/sql/country_osm_grid.sql)) and output a file (csv ?) with all the admins we want, correctly typed (and maybe even linked to each others).

The implementation of such project is left as an exercise to the reader :laughing: but as for the approach below I think something based on [libpostal's rules](https://github.com/openvenues/libpostal/blob/master/resources/boundaries/osm/) is the best way to go, even if it might not be up to date.

:white_check_mark: hide the complexity outside of mimir
:white_check_mark: the output file could be useful to other projects (having a structured dataset with admins hierarchy could be quite nice !)
:white_check_mark: could make the mimir import pipeline a bit more straightforward since we should import *first* the admins, but then we could import either OSM or bano/OA in any order
❌ Would be a bit difficult to keep close to the `dataset` notion, or we would to have a way to partition the output file for example to extract the admins for a country, a continent, ... But anyway, I'm not sure the `dataset` notion scale well
❌ not trivial to implement

### More clever osm2mimir

osm2mimir could use [libpostal's rules](https://github.com/openvenues/libpostal/blob/master/resources/boundaries/osm/). The big problem of this approach is that we need to know the country of an object, so for smaller than country import, we'll need to either give the country in cli, or use something like a [the countries shapes database](https://raw.githubusercontent.com/OSMNames/OSMNames/master/data/sql/country_osm_grid.sql) to be able to know if an object is in a country.

:white_check_mark: fit more in the mimir architecture
:white_check_mark: less executable to import the data, so easier to use
❌ would be mimir centric, cannot be useful to other projects
❌ not trivial to implement

## Conclusion
What do you think ?
Do you see stuff I have missed ? which solution seems the best for you ?

I hope we can work together toward the greatest world wide :world_map:  open source geocoder :sparkling_heart:

**Comment by TeXitoi** [comment]
I was basically just thinking of tagging the admin "use in label" or something like that (important, relevant...). And then just use the ordered matched admins in the label. Maybe that's not enough and high level information is needed.

libpostal's rules look great, simple enough and quite complete.

I have no real reason avoiding an intermediate file. It may be tricky to create a csv with all the info we want, shapes in wkt in csv is quite dirty. If you want a json output, you'll have about what's in the munin_admin database.

There is a lot of work that is already done in mimir about admin extraction from OSM, telling only libpostal rules to apply for the work to be done. Thus, it may be simpler to begin the binary here. Or we'll need to externalize a lib about admin on OSM over osmpbfreader.

**Comment by antoine-de** [comment]
Ok, so you're more for the external file solution ? (it's our choice too since it can be useful to others)

Is @kinnou02 ok with this ? it will mean that your import process becomes a bit more complex,
you'll have either to download an export in our server (either a world one or a filtered one), or run the exporter on your side to create the file before feeding it to `admin2mimir`

I feel it's a more robust solution but it will also make mimir a bit more complex to use (another mandatory executable to run on some data to fetch elsewhere)

**Comment by TeXitoi** [comment]
Whatever, I want a lib to manage all that. Everything can be in this repo, or on another, with code mutualized. I need to be able to generate this file myself. And, one time you can import the file, there is almost nothing to do to import inside admin2mimir.

With that, we can choose to do the osmadmin2mimir directly if needed.

We will need to have a period when we can use admin2mimir or osm2mimir for the migration period.

**Comment by antoine-de** [comment]
I think it's better to put the project outside mimir, so I've created a separate repositoy (ut this will force us to refacto a bit mimir to be able to use some code outside it)

The repository has not much in it for the moment, but we'll discuss needs and architecture in it
https://github.com/QwantResearch/cosmogony

**Comment by antoine-de** [comment]
are you sure you want a library to do this ?

I'm not sure yet, but it seems libpostal python's scripts can help a lot in the admin file creation (they seems to even handle a merge with quattroshapes that might help in some regions). I'm not sure of this at all, i need to dig deeper into those scripts (they are not documented much 😢 )

If those scripts works, I'm tempted to wrap those in a docker backed script (+ some rust code to create the hierarchy that's missing in libpostal) to generate a admin_hierarchy file from a .pbf.
So the mimir workflow would be either to generate a hierarchy file as a preprocess, or to download it from our server directly.

wouldn't that be acceptable for mimir ?

**Comment by kinnou02** [comment]
Sorry, I forgot about this.
I like the idea of having an intermediate step that extract all the admins that way we can inject is directly into mimir. It can be done in this repository or in another i don't really care honestly.
However I have a preference for a library as it will be easier for us to integrate directly in mimir, but if libpostale do already much of the works it will be easier and faster to only wrap them like you sugested.
In that case it will greatly help if the generated file is publicly accessible, it can be published into a github repository (we can use https://rawgit.com/ to serve it).

I think I have responded to most of your questions, but if not don't hesite to poke me

**Comment by TeXitoi** [comment]
Warning on the performances.

**Comment by antoine-de** [comment]
for hosting with rawgit ?

We definitely have to serve the generated file, we'll see how we do it (github, amazon opendata s3, or we could host it ourselves if I can convince our cloud team :stuck_out_tongue_winking_eye: )
the problem with the hosting is the ability to get a subset of the world (either by providing some split like geofabrik, or by providing tools to easily get a subset from a world file)


I don't think we'll use libpostal even if there are tons of interesting stuff in their preprocess because I find the scripts quite difficult to use :cry:

**Comment by pbougue** [comment]
Having a component to extract/manage admin looks great, yes.

The issues I am worried that are not covered (or just a bit) in this conversation are:
* regional/subset data retrieval (the extract runtime is probably gonna be suuuuper long, so we will want to have a partial and decorrelated way of retreiving data from the base created : quadtree/ES)
* regional/subset data update (we don't want database to ever inflate just because ids are changing)
* less important : manage geographic subjectivity (china vs. japan vs. US on some pacific islands, etc.)

So I'm not super fan of a lib, this would probably cost a too long integration time if I understood correctly what we would do with it.
On the other end, maintaining a server (rawgit or smarter) has it's price, but it looks better.

PS:
* Do we want to version data? And if yes, to what purpose? Not for history studies, maybe for mistake corrections, but the cost might be high.
