### ISSUE TITLE
Better API framework

### ISSUE THREAD

**Issue by antoine-de** [CanalTP/mimirsbrunn#180]
I open an issue about the fact that [rustless](https://github.com/rustless/rustless), the framework used in bragi is dead and we should migrate from it.

The alternative I see (don't hesitate if there are others):
### [Rocket](https://crates.io/crates/rocket)
the best one as I see it, but still stuck in nightly (for [quite a long time](https://github.com/SergioBenitez/Rocket/issues/19) :sob: )

### [Gotham](https://crates.io/crates/gotham)

fairly new but async and seems nice, even if argument parsing does not seems as shiny as rocket.
Since it's new we don't really know if it will die as rustless or not...

### [Rouille](https://crates.io/crates/rouille)
quite low level, I don't know it well

### [Iron](https://crates.io/crates/iron)
the more used, but quite old and not as shiny as the others

## which one should be chosen ?

* based on crates download (there is quite some differences :astonished: ) , I'd say Iron > Rouille > Rocket > Gotham
* based on the project activity, I'd say Rocket > Gotham > Rouille > Iron
* based on the number of core contributor (> +1000Loc) I'd say Iron | Gotham (2 main contributors) > Rouille | Rocket (only one)
* Based on my preferences I'd say Rocket :rocket: 

what's your though on this ?

**Comment by TeXitoi** [comment]
There is also raw hyper.

With an async framework, there is also the question of rs-es not supporting yet async.

**Comment by TeXitoi** [comment]
I'm against rocket because if we let this project sleep for some times, unstable rust can become problematic.

**Comment by antoine-de** [comment]
there is a newcomer that doesn't seem bad: https://actix.rs/

seems to have async handling and strongly typed parameter/results
