### ISSUE TITLE
filter an api query

### ISSUE THREAD

**Issue by cvenet30980** [CanalTP/mimirsbrunn#184]
Can we add filters in a API query ?
example : 
i want query poi in Paris http://localhost:4000/autocomplete?q=paris&osm_tag=type:poi
i don't want poi in Paris http://localhost:4000/autocomplete?q=paris&osm_tag=type:poi

thks

**Comment by antoine-de** [comment]
yes you can (seems like the API documentation is quite insufficient :stuck_out_tongue_winking_eye: )

to get the poi: `type=poi`
to not get any poi, just give the list of type you want (like in navitia)
`type=city&type=street&type=house` (and maybe `type=public_transport:stop_area`

**Comment by cvenet30980** [comment]
Thks for your answer

It's works
