### ISSUE TITLE
Handle osm2mimir CLI parameters correctly

### ISSUE THREAD

**Issue by antoine-de** [CanalTP/mimirsbrunn#189]
Hi,

for the moment:
* `--import-admin` is useless
* less important but I feel that `--import-street` is mandatory (or at least should be defaulted to `true`)

The second point is just an ergonomic issue, but the first one is a pain since I'd like to be able to *not* import the admin (and use the new cosmogony for it), but fixing the parameter handling will break some integration (people forgetting to pass `--import-admin` won't have anything anymore.

What is the right way to handle this ?

Clap bool argument only seems to work as flag, we can't say `--import-admins=false`, so should we reverse and add `--no-*` parameters ?
or move the string parameters and check `true`/`false`

can we change the default ?

**Comment by antoine-de** [comment]
did you had time to think on this ?

I'll need this for the cosmogony reading

**Comment by TeXitoi** [comment]
We are OK to fix the `--import-admin`. Using `--import-admin=false` is more problematic as it will break the interface.

I don't get why `--import-street` is mandatory, you can import POI without street.

**Comment by TeXitoi** [comment]
if you want to reverse, you need a `--skip-something`, but that's not really the idea.

**Comment by antoine-de** [comment]
yes the `import-street` is not mandatory it's just seems a good default value

In a more general point of view I think we screwd up those boolean flags.
We should have reversed them so `osm2mimir` would without parameters import everything instead of just doing nothing :stuck_out_tongue_winking_eye: 

for my immediate problem it's not important I just need to be able not to import city (so remocing the default value is fine), it's just that without those kind of sugar `mimir` is a bit harder to use for a newcomer.
