### ISSUE TITLE
Add tests on existing code

### ISSUE THREAD

**Issue by pbougue** [CanalTP/mimirsbrunn#20]
Now that we have an integration framework we should add tests on:

- [x] No street and admin import from bano
- [x] webservice (bragi)
- [x] real bano2mimir tests (complex requests)
- [x] real osm2mimir tests (complex requests, admin)
- [ ] bano2mimir taking either file or directory for input

**Comment by antoine-de** [comment]
no " bano2mimir taking either file or directory for input", but I'm not sure it's really relevent, I close the issue

**Comment by pbougue** [comment]
fine for me
