### ISSUE TITLE
Handle admin weight with cosmogony

### ISSUE THREAD

**Issue by antoine-de** [CanalTP/mimirsbrunn#206]
For the moment the admin weight (used to priorize the administrative regions in the search) is the number of street in an admin

If the admin comes from [cosmogony](https://github.com/osm-without-borders/cosmogony) it's more difficult to do this (since we don't know the number of street while importing the admin)

How do you think we have compute a relevant weigh now ?

One idea would be to take the `population` from osm but the tag is not often filled.

We could also use the `wikidata` id and look for the population in wikidata (or other stats), but either cosmogony or mimir will become dependent of a wikidata dump :cry: 

Do you have better ideas ?

**Comment by amatissart** [comment]
Actually we could stick to the current strategy and compute the weights in osm2mimir (based on the number of streets) . All admins would then be updated into elasticsearch with their new weights.

The drawback here is that it would require osm2mimir to be the first importer to run after cosmogony. (Unless other importers such as openaddresses2mimir can implement their own weights ?)

**Comment by TeXitoi** [comment]
That would be a circular dep, as osm2mimir would depends on the cosmogony admins.

I think that using the osm population would be OK, with no information setted to 0. We can assume that if the field is not provided, this admin is not so important. I think it would do the job for a first try.

**Comment by antoine-de** [comment]
I don't think it creates a circular dependency, `osm2mimir` would fetch the admins in `ES` and update/publish back their weight

the problem of the population is that the information would be very scares, I fear that the results will not be very good :confused:

**Comment by TeXitoi** [comment]
Ha, you mean osm2mimir would *modify* the admins? OK, why not.

**Comment by TeXitoi** [comment]
The weight is not so important.

**Comment by TeXitoi** [comment]
You'll have a weight for Paris and Lyon. The important thing is that the good solution is in the 3 first results. I think we need not overestimate the importance of that before having real data.

**Comment by antoine-de** [comment]
the admin weight seems ok as they are.

Can we close this ?

**Comment by antoine-de** [comment]
it seems everybody is ok with the closing of this issue :stuck_out_tongue_winking_eye:
