### ISSUE TITLE
rename Street's `street_name` to `name`

### ISSUE THREAD

**Issue by antoine-de** [CanalTP/mimirsbrunn#212]
for the moment the `Street`s have a field `street_name` whereas other objects have a `name` attribute.

the field being separated means that #211 cannot boost the query.

this results in subperformant query.

for example the query
`"Rue de Bouxwiller Bouxwiller"` returns all the streets of the `Bouxwiller` city and the street `Bouxwiller` of other cities (with or without #211, the 2 first results on navitia are `Rue de Bouxwiller (Strasbourg)` and `Rue de Niedersoultzbach (Bouxwiller)`).

renaming the field `street_name` to `name` fixes this, but It's a breaking change.

Is it fine for you if we duplicate the field for the migration ? do you see a better way to do this ? is it fine for you ?

**Comment by kinnou02** [comment]
It's fine to duplicate field for migration, it's the recommended way to do it.
