### ISSUE TITLE
Make mimir objects thread-safe

### ISSUE THREAD

**Issue by amatissart** [CanalTP/mimirsbrunn#218]
One more issue on our path to let mimirsbrunn go worldwide :earth_africa: !  
We did some experiments to optimize large imports using multiple threads.

As far as I can see, there are currently two blocking issues to make that possible:
 * `<Rc<mimir::Admin>>`, that could be replaced with `<Arc<mimir::Admin>>` in all structs. What are the drawbacks of such a change?
 * Admin.weight uses `Cell<f64>` to update weights during some imports. I am not sure about this one. But something like `Arc<RwLock<f64>>` could do the trick, unless we find another way to handle weights and avoid interior mutability when it's not necessary?

Here is an implementation of these changes (usable, but needs a better error handling):
https://github.com/CanalTP/mimirsbrunn/compare/master...amatissart:threadSafe

As an example, I tried to run an importer (fetching rows from postgres) on multiple threads using [**rayon**](https://github.com/rayon-rs/rayon). 
See https://github.com/amatissart/fafnir/blob/multithread/src/lib.rs#L167
That works, but is still a bit cumbersome: [`par_chunks`](https://docs.rs/rayon/1.0.1/rayon/slice/trait.ParallelSlice.html#method.par_chunks) is used to initialize `Rubber` in each thread. Maybe there is a better way.

In the end, that could help to optimize all importers such as "osm2mimir", that reads data in parallel, and then imports objects in a single thread.

What do you think ? Do I overlook something?

**Comment by TeXitoi** [comment]
Changing from Rc to Arc is OK.

You don't need `Arc<RwLock<f64>>`, `RwLock<f64` is sufficient. I'd prefer an Atomic. We can do a Weight object that wrap an `AtomicU32` to get a value between 0 and 1.

**Comment by TeXitoi** [comment]
Using rayon will not do the trick, you'll load everything into ram before running anything in parallel. You can look at https://crates.io/crates/par_map the parallelization will be trivial. Any feedbacks or improvement welcome on this crate. Used by osmpbfreader.

**Comment by TeXitoi** [comment]
For `RwLock`, this crate is very interesting: https://crates.io/crates/parking_lot

**Comment by amatissart** [comment]
Actually we need a clonable `Admin`, so `RwLock` is not sufficient as is.  

Thanks, I'll take a look at "par_map" to avoid building these ugly chunks.

**Comment by TeXitoi** [comment]
You really need a clonable Admin? Having Arc<Admin> clonable is not enough?

**Comment by TeXitoi** [comment]
You can also implement Clone for Admin by hand and doing the copy of the value in the RwLock.

**Comment by TeXitoi** [comment]
But different semantics, thus, why do you need Admin to be clonable?

**Comment by amatissart** [comment]
`Admin` is already clonable, and that is used in several contexts, especially in [admin_geofinder.rs](https://github.com/CanalTP/mimirsbrunn/blob/b2a219e/src/admin_geofinder.rs#L119) to build iterators on all admins with or without boundary.

Or to include itself in `.admins()`: https://github.com/CanalTP/mimirsbrunn/blob/b2a219e05727b4858ffd36782cbb7810be85f63f/libs/mimir/src/objects.rs#L414-L422
