### ISSUE TITLE
Filter the autocomplete results

### ISSUE THREAD

**Issue by nlehuby** [CanalTP/mimirsbrunn#243]
For now, if you want to filter the search results from Mimir, you can get some inconsistencies. See for instance 
* this issue: https://github.com/CanalTP/mimirsbrunn/issues/230
* this PR, with some solutions and some new issues: https://github.com/CanalTP/mimirsbrunn/pull/235

So, what can we do ?

# Our constraints

## Retrocompat

`autocomplete?q=foo&type=city` should get you only zones with `city` as `zone_type`

## Coherency between question and answer

We have a `type` field in our answer. 
POIs have also a `poi_types` field.

For the sake of consistency, if we have filter on `type` or on `poi_type`, we shoud give the parameter the same name, and it should accept as values only what we can have as value in theses fields in our answer.

## Geocodejson

We need to have a `type` field in the answer for each element.
The specs also recommends some values (`house` for addresses, `street` for streets, etc)

# What do we want

## Filter by type

We want to filter in any kind of Mimir type: zones, address, streets, pois and stop_areas.

We also want to combine these filters to keep many types.

But we should be aware that there is an inconsistency in the current bragi response as `Zones` actually have a `type` which is not `zone` (a state_district has `type` = `state_district`) :shit:

like:

```json=
"geocoding": {
    "citycode": "75",
    "id": "admin:osm:relation:71525",
    "label": "Paris, Île-de-France, France",
    "level": 6,
    "name": "Paris",
    "type": "state_district" // <-- it's not a classic type, it's a ZoneType
}
```

## Filter by subtype

Some Mimir types have subtypes: POIs have `poi_types` and zones have `zone_type` and we should be able to filter on those types too.

As said before, the zones are not consistent in this matter as their `zone_type` is hold by their `type` :stuck_out_tongue_winking_eye: 

# Proposals

## Solution 1

2 parameters:
* `type`
* `poi_type` or `zone_type`

**Solution 1a**:

We fix the coherency issue between the question and the answer: we change the type of the admin to `zone` (or `administrative_region` but I find it less generic as we might want to add non administrative regions like `parc du mercantour` or `disneyland paris`) and add a `zone_type` field in the `Zones`.

This is the cleaner option, but it breaks the retrocompat.

**Solution 1b**:

We do not change the answer, and keep the inconsistency : you ask for `type = zone` and `zone_type = state_district` and you get `type = state_district` 

### how do we handle strange questions?

We need to decide what to do if we only get the `subtype` parameter (but no `type` paramater): `/autocomplete?q=foo&zone_type[]=country`

We could either assume that the user wanted to also filter by type. 

Or we could error instead of trying to guess what the user want.
I prefer this option, because with good error message, we can teach the user how the API works (and as we don't have any doc about the API parameter for now, this is better than to have to read the source code to find the name of the parameter and its accepted values)

## Solution 2

Only one `type` parameter.

It could have as value anything in the usual Mimir response:
* `city`, `state_district`, `state`, etc
* `poi`
* `house`, `street`

We cannot filter by zone (or we have to list all the zone types in the type parameter)

We cannot filter by poi types.

What do you think ?

**Comment by antoine-de** [comment]
pouet, did you had time to think about this ? :ping_pong:

**Comment by TeXitoi** [comment]
pouet, nop :stuck_out_tongue:

**Comment by pbougue** [comment]
Thought about it a bit along #235 ...
Also voting for 1a (no opinion on error vs. silently guessing user's request).
It breaks retro-compat but we shouldn't be affected (much?), or if it's the case it's easy to anticipate and deploy a navitia version that's compatible for both.
Not always super easy to clean interface, but we should do it as long as it's doable (and it's quite cheap in that case).

**Comment by amatissart** [comment]
After discussion :
 
3 filter parameters will be accepted in the query : 
 * `type`: values among existing types, and a new type `zone`. 
`type=city` will stay equivalent to `type=zone`
 * `zone_type[]` (requires `type=zone`)
 * `poi_type[]` (requires `type=poi`)

Response format:
 * existing poi format is ok
 * admins : geocoding object includes `{"type":"zone", "zone_type": "city"}` instead of current `{"type":"city"}`
