### ISSUE TITLE
Better control of number of shards / replicas

### ISSUE THREAD

**Issue by antoine-de** [CanalTP/mimirsbrunn#267]
For the moment the number of shards for each index is "hardcoded" in each index json settings and the number of replica is the default value (1 replica).

I don't think this is flexible enough.

I think we should have some ways to change it to fine tune mimir on big clusters.

We propose to add 2 cli parameters on each data importer:
* `--nb-shards`
* `--nb-replicas`

`osm2mimir` is a bit of a problem since it can import several types, so I guess we can add for it:
`--nb-poi-shards` `--nb-admin-shards` `--nb-street-shards` and the same for the replicas.

Is it ok for you if the number of shard default value move from being [in the `<type>_settings.json`](https://github.com/CanalTP/mimirsbrunn/blob/master/json/street_settings.json#L4] to being in the structopt struct? I don't think we can keep them in the json template as those json are updated for [all types before each import](https://github.com/CanalTP/mimirsbrunn/blob/master/src/bin/osm2mimir.rs#L93) with the [initialize_template](thttps://github.com/CanalTP/mimirsbrunn/blob/master/src/bin/osm2mimir.rs#L93).

As a first implementation I think we can do a dumb json replacement on the generic index settings `settings.json` [like we do for the synonyms](https://github.com/CanalTP/mimirsbrunn/blob/master/libs/mimir/src/rubber.rs#L284) for the number of shards / replicas.

In  a second iteration we could reduce the workload on the ES cluster on settings the number of replica to `0` before the bulk insert and increasing it afterward for ES to only do a copy (as it is mentioned in the [ES documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-update-settings.html#bulk). As changing the number of replica is an asynchronous operation, it will be a bit more difficult to trigger the `publish_index`, so I guess we should first check if it is worth it.

Is it ok for you?

**Comment by kinnou02** [comment]
It's ok for me!
ideally we should have the same default values than before.

**Comment by TeXitoi** [comment]
OK for me too.
