### ISSUE TITLE
Doesn't find villages

### ISSUE THREAD

**Issue by yotamN** [CanalTP/mimirsbrunn#277]
The search doesn't find any villages, not as an area and not as a point.

**Comment by TeXitoi** [comment]
Can you please be more specific? Which village? What data did you import?

**Comment by yotamN** [comment]
I tried it through https://www.qwant.com/maps/
I searched for HaGoshrim and הגושרים but they both didn't find the village (https://www.openstreetmap.org/way/87167739)

**Comment by nlehuby** [comment]
Thanks for your feedback @yotamN 
Qwant Maps issues should be reported in this repo: https://github.com/QwantResearch/qwantmaps/

For now, you can only search for places that are [administrative boundaries](https://wiki.openstreetmap.org/wiki/Tag:boundary%3Dadministrative) in OSM.
There is still some work to do in Cosmogony to get the ones tagged as way (like your example) and compute some kind of shapes for the ones that does not have one yet (see https://github.com/osm-without-borders/cosmogony/issues/19).

If you want to help us with this topic, you can:
* improve Cosmogony by telling us about the number of administrative zone in your country and how they are mapped in OSM
* enrich [geocoder-tester](https://github.com/qwantresearch/geocoder-tester) (our test suites) with queries for your country

Check out https://github.com/QwantResearch/qwantmaps/blob/master/contributing.md#Expanding
