### ISSUE TITLE
Filter pois in bragi

### ISSUE THREAD

**Issue by antoine-de** [CanalTP/mimirsbrunn#314]
Some clients want to see only their POIs and not see the other POIs. They also don't want the other clients to see their POIs.

To do this I think we can use a mechanism close to the stops's.

 * add a `poi_dataset` bragi parameter (like [the pt_dataset](https://github.com/CanalTP/mimirsbrunn/blob/release/libs/bragi/src/routes/autocomplete.rs#L62)) in `/autocomplete`, `/features`
* since we don't need an equivalent to [the global stop index](https://github.com/CanalTP/mimirsbrunn/blob/release/src/stops.rs#L42), I think we can only use this `poi_dataset` parameter to filter on the queried ES index:
  * Some(poi_dataset) => index_searched += "munin_poi_{poi_dataset}"
  * None => index_searched += "munin_poi"
and we do not alias pois from `poi2mimir` in `munin_poi`

what do you think about this @kinnou02 @riendegris ?

Some integration tests are also required, maybe in the same file as #313 
Inspiration for the tests can be taken from [there](https://github.com/CanalTP/mimirsbrunn/blob/release/tests/bragi_stops_test.rs#L175)

**Comment by riendegris** [comment]
This issue was addressed with #332
