### ISSUE TITLE
Doesn't find places with unknown tags

### ISSUE THREAD

**Issue by yotamN** [CanalTP/mimirsbrunn#315]
It seems that a lot of places that are tagged in a way that mimir does not understand are just not shown in the search results and it prevent me from finding a lot of things.  
For example a military area that is tagged `landuse=military` is not shown but also a less known tag like `water=stream_pool` is not shown.

**Comment by antoine-de** [comment]
hum it seems more related to the way qwant maps imports POI into mimir using [their custom tool](https://github.com/QwantResearch/fafnir), no @amatissart @jbgriesner @GuillaumeGomez ?

**Comment by amatissart** [comment]
tracked in https://github.com/QwantResearch/qwantmaps/issues/83
