### ISSUE TITLE
Compoment loading order and missing index

### ISSUE THREAD

**Issue by frodrigo** [CanalTP/mimirsbrunn#346]
There is an order on component loading?

osm2mimir miss the ES index. But bano2mimir create its own index.

**Comment by riendegris** [comment]
Hello Frederic,

yes, there is an order for loading the data:
1. You need to have cosmogony load the administrative regions
2. Then bano load the streets
3. Then, I think, osm and ntfs in no particular order.

I have recently finished a script to load data into elasticsearch, its in `scripts/import2mimir.sh`, and you can see how these binaries are called. The script grew out of a personal need, and may not be very robust.

Did I answer your question?

**Comment by kinnou02** [comment]
`osm2mimir` try to load the admins from ES if the flag ` --import-admin` isn't set, if you don't want to use cosmogony you can directly use `osm2mimir` to build them, it is a bit dumb and only use admin_level to do so with `--level`, in France this works quite well and cosmogony isn't required even if it improve the quality;

**Comment by frodrigo** [comment]
Ok. Thank.

I lost lot of time trying to figure why there is no index and how to create it by starting with OSM import. A check for the index and an error message could be clever.
