### ISSUE TITLE
cosmogony2mimir dataset and lang not documented

### ISSUE THREAD

**Issue by Fi3** [CanalTP/mimirsbrunn#407]
The option `dataset` and `lang` are not documented. Is not obvious that if  different region are imported  using different files the option `dataset` must be set in order to not overwrite the previous import. Also the `lang` option is not documented, still not sure of what it do.

**Comment by riendegris** [comment]
Hello Fi3,

We certainly need to improve the documentation, and we're working on it. Having said that, for your problem at hand, you can use the dataset (`-d`, or `--dataset`) to partition your elasticsearch index. For example, you could use the same input file, and two distinct dataset values, that will create two distincts elasticsearch indices. You can then query them using the `pt_dataset[]` query parameter with bragi.

As for the lang, it is used by the program to build i18n names and labels.

These options are seen when you execute `cosmogony2mimir --help`.

I hope this helps, let me know if that answers your question correctly.

**Comment by Fi3** [comment]
Yes ofc. Thanks you. For me the problem was that when importing two files with no `dataset` specified the importer overwrite the first and in my opinion this is not very intuitive. So I just wanted to point out that from the user point of view, have this behavior specified somewhere in the docs would be great.
