### ISSUE TITLE
missing housenumber field with bano file

### ISSUE THREAD

**Issue by Qespion** [CanalTP/mimirsbrunn#408]
i'm using a script to import data into mimirbrunn.
The script import cosmogony data using `cosmogony2mimir` then bano data using `bano2mimir` and finaly osm data using `osm2mimir`.
I don't see any error output while doing the import. But when i do a query on an address. The response have every field exept for the housenumber.

**Comment by riendegris** [comment]
Hello Qespion,

I've had similar issues in the past with logging. As you can see in `libs/mimir/src/lib.rs`, logging is controlled, like is customary in many a rust project, by the `RUST_LOG` env variable. Maybe you need to set it to a different [value](https://docs.rs/slog/2.4.1/slog/static.LOG_LEVEL_NAMES.html).
Maybe if you show me the script, and the output you have I may be able to help you further.

**Comment by Qespion** [comment]
Hi thanks for your answer

Here is a bash script example.
`
REGION="ile-de-france"
POSTAL_CODES="75 92 93 94 95 78 91 77"
# Download
echo "Downloading..."
curl "https://download.geofabrik.de/europe/france/$REGION-latest.osm.pbf" -o "/data/osm/europe/france/$REGION.pbf"
for POSTAL_CODE in $POSTAL_CODES; do
    curl "https://adresse.data.gouv.fr/data/ban/adresses/latest/csv/adresses-$POSTAL_CODE.csv.gz" -o "/data/ban/adresses-$POSTAL_CODE.csv.gz"
    curl "https://adresse.data.gouv.fr/data/ban/adresses/latest/csv/lieux-dits-$POSTAL_CODE-beta.csv.gz" -o "/data/ban/lieux-dits-$POSTAL_CODE-beta.csv.gz"
    curl "http://bano.openstreetmap.fr/data/bano-$POSTAL_CODE.csv" -o "/data/bano/bano-$POSTAL_CODE.csv"
    curl "http://bano.openstreetmap.fr/data/bano-$POSTAL_CODE.json.gz" -o "/data/bano/bano-$POSTAL_CODE.json.gz"
done

# Generate
echo "Generating..."
docker run -v /data:/data -it mimir-tools /bin/sh -c "cosmogony --country-code FR -i \"/data/osm/europe/france/$REGION.pbf\" -o \"/data/cosmogony/europe/france/$REGION.json.gz\""

echo "Importing..."
docker run -v /data:/data --network="host" -it mimir-tools /bin/sh -c "cosmogony2mimir -c http://elasticsearch:9200 -i \"/data/cosmogony/europe/france/$REGION.json.gz\""

for POSTAL_CODE in $POSTAL_CODES
do
    docker run -v /data:/data/ --network="host" -it mimir-tools /bin/sh -c "bano2mimir -c http://elasticsearch:9200 -i \"/data/bano/bano-$POSTAL_CODE.csv\""
done

docker run -v /data:/data --network="host" -it mimir-tools /bin/sh -c "osm2mimir -c http://elasticsearch:9200 --import-way --import-poi -i \"/data/osm/europe/france/$REGION.pbf\""
`
I think i found an answer. It seems that when i import a BANO file using bano2mimir. It is overwriting on previous entries. For example when i use this script i only get data from the last department. A quick fix i'm using is agregating all the bano file into one and loading it once with `bano2mimir`.
But what if i want to add more data after ? I'm still not sure i have the right approach.

**Comment by amatissart** [comment]
`bano2mimir -i` accepts a folder of .csv files, so you could import all departements in a single run by providing such a folder.

Alternatively you can also specify a dataset name with the `--dataset` option for each run, to avoid overwriting previous entries.

Each run of `bano2mimir` (also true for other mimir importers) creates a new Elasticsearch index, namespaced by the dataset name and the type of objects (addresses in this case). At the end of a successful run, any preexisting index with the same type and dataset name is removed.

**Comment by Qespion** [comment]
Using `--dataset` with a specific name for each departments. I have the right behavior. Thanks for the quick answer
