### ISSUE TITLE
Could this be used for address verification?

### ISSUE THREAD

**Issue by gelsas** [CanalTP/mimirsbrunn#470]
Hi,

I am currently trying to create an wordpress plugin for woocommerce and I was wondering if this project could be used for address verification.

What I mean is lets say customer has entered an incomplete address like this:

769 Coakley Drive, San Jose CA 9511 United States

or like this

769 Coakley Drive, 95117 United States

Could mimirsbrunn be used to try to autocomplete/auto suggest possible address, to make it a full address?

**Comment by crocme10** [comment]
Hello,

yes, mimirsbrunn could be used for that purpose.  When we store an address, we build a 'label' for it, which is supposed to be the full address. If you enter an incomplete address, mimir will try to find the best candidates to match your input.

Did this answer address (with some delays, sorry) your question?
