### ISSUE TITLE
Invalid "_type"

### ISSUE THREAD

**Issue by crocme10** [CanalTP/mimirsbrunn#621]
A typical document is stored in Elasticsearch with

```json
{
  "_index": "munin_addr_fr_20211105_114052_063707916",
  "_type": "_doc",
  "_id": "addr:2.952773;48.383767:2",
  "_version": 1,
  "_seq_no": 240599,
  "_primary_term": 1,
  "found": true,
  "_source": {
   ...
  }
}
```

The "_type" should reflect the place type.

**Comment by crocme10** [comment]
This information is also found in "_source.type", which may be enough?

**Comment by crocme10** [comment]
"_type" should not be used, per [Elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/7.15/removal-of-types.html)
We'll use "_source.type" instead

**Comment by remi-dupre** [comment]
This is already handled by serde's tag, eg. [here](https://github.com/CanalTP/mimirsbrunn/blob/master/libs/places/src/poi.rs#L15) for POIs.

Do you have something else in mind?

**Comment by crocme10** [comment]
Yes, I am thinking of [constant keywords](https://www.elastic.co/guide/en/elasticsearch/reference/master/faster-filtering-with-constant-keyword.html).

**Comment by crocme10** [comment]
constant keywords were added in #638
